import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import AuthProvider from '@/components/auth/AuthProvider';
import { ModalProvider } from '@/context/ModalContext';
import AuthModal from '@/components/auth/AuthModal';
import Header from '@/components/Header';
import Footer from '@/components/Footer'

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className={`${inter.className} antialiased flex flex-col min-h-screen bg-blue-50`}>
        <AuthProvider>
          <ModalProvider>
            <Header />
            <main  className="flex-grow" >{children}</main>
            <Footer />
            <AuthModal /> 
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}